### ISSUE TITLE
sort alphabetically

### ISSUE THREAD

**Issue by sanikolaev** [db-benchmarks/ui#10]
Let's try to keep the columns sorted alphabetically. It can help people compare different versions/commits of the same db, since they will go one column after another.

**Comment by db-benchmarks-team** [comment]
➤ Klim Todrik commented:
 

 
done

**Comment by db-benchmarks-team** [comment]
➤ Sergey Nikolaev commented:
 

 
Please specify the commit in which this change is available. It doesn't seem to be working to me in the latest commit.
