### ISSUE TITLE
select db type automatically if it's a single type

### ISSUE THREAD

**Issue by sanikolaev** [db-benchmarks/ui#12]
In cases like this when there's only one type for engine:

<img width="656" alt="image" src="https://user-images.githubusercontent.com/28719845/174939980-fd16d3d9-ed77-4dfb-9e03-50573558d71c.png">

Let's select it automatically on clicking on the engine.

**Comment by db-benchmarks-team** [comment]
➤ Klim Todrik commented:
 

 
done

**Comment by sanikolaev** [comment]
I can't see it working in the latest commit https://github.com/db-benchmarks/ui/commit/cae03a9be056362d3b570b177a9bab87eebd8bcf

**Comment by db-benchmarks-team** [comment]
➤ Klim Todrik commented:
 

 
done
