### ISSUE TITLE
visualize engine/dataset info

### ISSUE THREAD

**Issue by sanikolaev** [db-benchmarks/ui#13]
Let's add:
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/28719845/174966909-2482b9c2-b13f-42a9-8b88-06a0373fa846.png">

and on click on the icon show a modal info which displays `results.info` from the db in tabs. The value in the db can be:

```json
{
   "version":"1.15.2",
   "manticoreVersion":"1.15.2",
   "manticoreCommit":"b4cb_b0bc",
   "manticoreCommitTime":1652824800,
   "typeAppendum":"",
   "url":"https://manticoresearch.com/",
   "description":"Manticore Search is a multi-storage database designed specifically for search, including full-text search",
   "datasetCount":116543900,
   "datasetSampleDocument":{
      "author_comment_count":11,
      "comment_author":"Quizzy",
      "comment_id":3985756,
      "comment_ranking":10,
      "comment_text":"Makes sense for Verizon, and if they are being greedy, others will step in to fill the void.",
      "story_author":"joedev",
      "story_comment_count":13,
      "story_id":3985069,
      "story_text":""
   }
}
```

Some of the fields are stable:
* datasetSampleDocument ("Sample document") 
* datasetCount ("Documents count in the dataset")
* description ("Database description")
* url ("Database url", should be clickable)

Others don't need any visualization:
* typeAppendum

The others depend on an engine, e.g. for Manticore it can be:
```
   "version":"1.15.2",
   "manticoreVersion":"1.15.2",
   "manticoreCommit":"b4cb_b0bc",
   "manticoreCommitTime":1652824800,
```

**Comment by db-benchmarks-team** [comment]
➤ Klim Todrik commented:
 

 
https://manticoresearch.slack.com/archives/DARHC30BY/p1657119459220749

**Comment by db-benchmarks-team** [comment]
➤ Klim Todrik commented:
 

 
done
