### ISSUE TITLE
sort rows in Relative query processing time

### ISSUE THREAD

**Issue by sanikolaev** [db-benchmarks/ui#19]
Let's sort rows in the "Relative query processing time" in ascending order by the value.

**Comment by db-benchmarks-team** [comment]
➤ Klim Todrik commented:
 

 
done in https://github.com/db-benchmarks/ui/pull/21

**Comment by db-benchmarks-team** [comment]
➤ Sergey Nikolaev commented:
 

 
Reopening since there's a bug https://github.com/db-benchmarks/ui/pull/21#issuecomment-1231431085

**Comment by sanikolaev** [comment]
Fixed. PR merged.
