### ISSUE TITLE
Disable caching index

### ISSUE THREAD

**Issue by djklim87** [db-benchmarks/ui#36]
Sometimes after a new release we see that the old index.html is cached in the client browser and cause some troubles

**Comment by djklim87** [comment]
As it turned out, it's common problem in Vue.js and similar frameworks. And most often solution - just disable caching for index.html. Done in https://github.com/db-benchmarks/ui/commit/50ecbfb0e80fb1ea4b9fa9ad2d1ed86900d0c821

**Comment by sanikolaev** [comment]
Published.
