### ISSUE TITLE
cache=slowest gets lost

### ISSUE THREAD

**Issue by sanikolaev** [db-benchmarks/ui#37]
If you open 
https://db-benchmarks.com/?cache=slowest&engines=clickhouse_1_core_21.8.11.4%2Cmanticoresearch_1_core_6.0.2%2Cmeilisearch_1_core_1.1.1%2Cmysql_1_core_8.0.28%2Cpostgres_1_core_15.2+%28Debian+15.2-1.pgdg110%2B1%29&tests=hn_small&memory=1024&queries=0%2C1%2C2%2C5%2C6%2C7%2C8%2C16%2C17%2C18%2C19%2C20%2C21%2C22%2C26%2C27 even though there's `cache=slowest` in the url it will be ignored. The task is to fix it.

**Comment by djklim87** [comment]
Fixed in https://github.com/db-benchmarks/ui/commit/237ecb417a91c10112ad96a9daa01f06a06094ed

I deployed this changes to https://manticore.db-benchmarks.com/

**Comment by sanikolaev** [comment]
Published on https://db-benchmarks.com/
